apiVersion: v1
kind: Pod
metadata:
  name: marc-nginx
spec:
  restartPolicy: Always
  containers:
    - name: marc-nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: log
          mountPath: /var/log/marc
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: nginx-conf
      hostPath:
        path: /srv/marc_infra/nginx/nginx.conf
        type: File
    - name: log
      hostPath:
        path: /var/log/marc
        type: DirectoryOrCreate
